# coding: utf-8

"""
    Recipe Comparison

    This is a recipe comparer tool       

    The version of the OpenAPI document: 1.0.0
    Contact: megretson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.difference_object import DifferenceObject

class TestDifferenceObject(unittest.TestCase):
    """DifferenceObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DifferenceObject:
        """Test DifferenceObject
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DifferenceObject`
        """
        model = DifferenceObject()
        if include_optional:
            return DifferenceObject(
                recipe_field = 'rating',
                recipe_id = 1.337,
                make_id = 1.337,
                difference = openapi_client.models.difference.difference(
                    recipe = '', 
                    make = '', )
            )
        else:
            return DifferenceObject(
                recipe_field = 'rating',
                recipe_id = 1.337,
                make_id = 1.337,
                difference = openapi_client.models.difference.difference(
                    recipe = '', 
                    make = '', ),
        )
        """

    def testDifferenceObject(self):
        """Test DifferenceObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
