from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Step(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, step_id=None, step_text=None):  # noqa: E501
        """Step - a model defined in OpenAPI

        :param step_id: The step_id of this Step.  # noqa: E501
        :type step_id: float
        :param step_text: The step_text of this Step.  # noqa: E501
        :type step_text: str
        """
        self.openapi_types = {
            'step_id': float,
            'step_text': str
        }

        self.attribute_map = {
            'step_id': 'stepId',
            'step_text': 'stepText'
        }

        self._step_id = step_id
        self._step_text = step_text

    @classmethod
    def from_dict(cls, dikt) -> 'Step':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The step of this Step.  # noqa: E501
        :rtype: Step
        """
        return util.deserialize_model(dikt, cls)

    @property
    def step_id(self) -> float:
        """Gets the step_id of this Step.


        :return: The step_id of this Step.
        :rtype: float
        """
        return self._step_id

    @step_id.setter
    def step_id(self, step_id: float):
        """Sets the step_id of this Step.


        :param step_id: The step_id of this Step.
        :type step_id: float
        """

        self._step_id = step_id

    @property
    def step_text(self) -> str:
        """Gets the step_text of this Step.


        :return: The step_text of this Step.
        :rtype: str
        """
        return self._step_text

    @step_text.setter
    def step_text(self, step_text: str):
        """Sets the step_text of this Step.


        :param step_text: The step_text of this Step.
        :type step_text: str
        """

        self._step_text = step_text
