# coding: utf-8

# flake8: noqa
"""
    Recipe Comparison

    This is a recipe comparer tool       

    The version of the OpenAPI document: 1.0.0
    Contact: megretson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.difference import Difference
from openapi_client.models.difference_object import DifferenceObject
from openapi_client.models.ingredient import Ingredient
from openapi_client.models.ingredient_difference import IngredientDifference
from openapi_client.models.rating_difference import RatingDifference
from openapi_client.models.recipe import Recipe
from openapi_client.models.step import Step
from openapi_client.models.step_difference import StepDifference
from openapi_client.models.step_difference_all_of_difference import StepDifferenceAllOfDifference
