# coding: utf-8

"""
    Recipe Comparison

    This is a recipe comparer tool       

    The version of the OpenAPI document: 1.0.0
    Contact: megretson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "openapi-client"
VERSION = "1.0.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic-core == 2.4.0",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Recipe Comparison",
    author="OpenAPI Generator community",
    author_email="megretson@gmail.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Recipe Comparison"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="Apache 2.0",
    long_description_content_type='text/markdown',
    long_description="""\
    This is a recipe comparer tool       
    """,  # noqa: E501
    package_data={"openapi_client": ["py.typed"]},
)
