# coding: utf-8

"""
    Recipe Comparison

    This is a recipe comparer tool       

    The version of the OpenAPI document: 1.0.0
    Contact: megretson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_add_recipe(self) -> None:
        """Test case for add_recipe

        add a new recipe
        """
        pass

    def test_add_recipe_make(self) -> None:
        """Test case for add_recipe_make

        say that you made a recipe
        """
        pass

    def test_get_recipe_make(self) -> None:
        """Test case for get_recipe_make

        Recieve information on a given make of a recipe
        """
        pass

    def test_get_recipe_make_differences(self) -> None:
        """Test case for get_recipe_make_differences

        Recieve information on a given make of a recipe, including any variations between the make and the actual recipe
        """
        pass

    def test_update_recipe(self) -> None:
        """Test case for update_recipe

        update a recipe
        """
        pass


if __name__ == '__main__':
    unittest.main()
