# coding: utf-8

"""
    Recipe Comparison

    This is a recipe comparer tool       

    The version of the OpenAPI document: 1.0.0
    Contact: megretson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.step_difference_all_of_difference import StepDifferenceAllOfDifference

class TestStepDifferenceAllOfDifference(unittest.TestCase):
    """StepDifferenceAllOfDifference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StepDifferenceAllOfDifference:
        """Test StepDifferenceAllOfDifference
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StepDifferenceAllOfDifference`
        """
        model = StepDifferenceAllOfDifference()
        if include_optional:
            return StepDifferenceAllOfDifference(
                step_id = 1.337
            )
        else:
            return StepDifferenceAllOfDifference(
                step_id = 1.337,
        )
        """

    def testStepDifferenceAllOfDifference(self):
        """Test StepDifferenceAllOfDifference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
