# coding: utf-8

"""
    Recipe Comparison

    This is a recipe comparer tool       

    The version of the OpenAPI document: 1.0.0
    Contact: megretson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ingredient import Ingredient

class TestIngredient(unittest.TestCase):
    """Ingredient unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Ingredient:
        """Test Ingredient
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Ingredient`
        """
        model = Ingredient()
        if include_optional:
            return Ingredient(
                ingredient_id = 1.337,
                quantity = 1.337,
                measurement = '',
                ingredient_name = ''
            )
        else:
            return Ingredient(
        )
        """

    def testIngredient(self):
        """Test Ingredient"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
