# coding: utf-8

"""
    Recipe Comparison

    This is a recipe comparer tool       

    The version of the OpenAPI document: 1.0.0
    Contact: megretson@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ingredient_difference import IngredientDifference

class TestIngredientDifference(unittest.TestCase):
    """IngredientDifference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IngredientDifference:
        """Test IngredientDifference
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IngredientDifference`
        """
        model = IngredientDifference()
        if include_optional:
            return IngredientDifference(
                recipe_field = 'rating',
                recipe_id = 1.337,
                make_id = 1.337,
                difference = openapi_client.models.difference.difference(
                    recipe = '', 
                    make = '', ),
                ingredient_id = 1.337,
                ingredient_field = 'quantity'
            )
        else:
            return IngredientDifference(
                recipe_field = 'rating',
                recipe_id = 1.337,
                make_id = 1.337,
                difference = openapi_client.models.difference.difference(
                    recipe = '', 
                    make = '', ),
                ingredient_id = 1.337,
                ingredient_field = 'quantity',
        )
        """

    def testIngredientDifference(self):
        """Test IngredientDifference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
